title: Disruptive Angels
email: cronos@disruptiveangels.com
description: > # this means to ignore newlines until "baseurl:"
  Our Open Innovation Processes in collaboration with large companies, help us develop new ideas and fundamentals for the creations of new tech startups
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: DisruptiveAngel
github_username:  DisruptiveAngels

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
