title: Disruptive Angels
email: cronos@disruptiveangels.com
description: > # this means to ignore newlines until "baseurl:"
  Our Open Innovation Processes in collaboration with large companies, help us develop new ideas and fundamentals for the creations of new tech startups
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://disruptiveangels.com/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: DisruptiveAngel
github_username:  DisruptiveAngels
permalink: /blog/:title.html

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - yarn.lock
  - package.json
  - gulpfile.js
  - CNAME
  - node_modules
  - _assets