title: Changing the path of Innovation | Disruptive Angels
email: cronos@disruptiveangels.com
description: > # this means to ignore newlines until "baseurl:"
  We solve the most complex industrial challenges through state of the art customizable Technology and Open Innovation.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://disruptiveangels.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: DisruptiveAngel
github_username:  DisruptiveAngels
permalink: /blog/:title.html

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - yarn.lock
  - package.json
  - gulpfile.js
  - CNAME
  - node_modules
  - _assets
